### ISSUE TITLE
Broken with bleak==0.19.2

### ISSUE THREAD

**Issue by stever29** [mduran80/pymadoka#11]
Hello, 

Thanks for all the hard work on this!

The module is broken with bleak==0.19.2 (and presumably >= 0.19.0) due to asyncBleakScanner.get_discovered_devices() being removed: https://bleak.readthedocs.io/en/latest/api/scanner.html

I'm not an expert, but it seems to work if you update the pymadoka get_discovered_devices() to:
`    ...
    DISCOVERED_DEVICES_CACHE = scanner.discovered_devices                            
    return DISCOVERED_DEVICES_CACHE`

Thanks

**Comment by mduran80** [comment]
Already fixed in https://github.com/mduran80/pymadoka/commit/f8aef1febd2867673281f1181f5dca863919ab9b

**Comment by stever29** [comment]
Ah. Thanks. This came up as the HA integration broke and I'd forgotten this wasn't managed by HACS (and therefore didn't see there was an update pending!). Thanks again
